import type { NextPage } from 'next'
import Head from 'next/head'
import PageRevealer from '@components/PageRevealer/PageRevealer'

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Pakkaphong Akkabut - All about Sanviiz</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="container mx-auto">
				<div className="border border-red-500 py-60 text-center text-red-500 md:py-96">
					Content
				</div>
				<div className="text-white">
					<PageRevealer />
				</div>
			</div>
		</>
	)
}

export default Home
