import type { NextPage } from 'next'
import Head from 'next/head'
import TableOfContents from '@components/TableOfContents/TableOfContents'
import HeroSection from '@components/HeroSection/HeroSection'
import EducationSection from '@components/EducationSection/EducationSection'
import SkillSection from '@components/SkillSection/SkillSection'
import WorkSection from '@components/WorkSection/WorkSection'
import TechnicalProjectSection from '@components/TechnicalProjectSection/TechnicalProjectSection'
import BusinessProjectSection from '@components/BusinessProjectSection/BusinessProjectSection'

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Pakkaphong Akkabut - All about Sanviiz</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="container mx-auto max-w-5xl px-2 py-4 pt-6 xs:px-8 md:pt-4 xl:px-0">
				<HeroSection />
				<hr className="my-4 border-gray-200 transition-all dark:border-gray-700 sm:mx-auto md:my-6" />
				<div className="grid grid-cols-1 gap-4 lg:grid-cols-4">
					<div>
						<TableOfContents />
					</div>
					<div className="lg:col-span-3">
						<EducationSection />
						<SkillSection />
						<WorkSection />
						<TechnicalProjectSection />
						<BusinessProjectSection />
					</div>
				</div>
			</div>
		</>
	)
}

export default Home
